In [ ]:
%%capture
!apt install octave

In [ ]:
import numpy as np

# Convolve

In [ ]:
%%writefile conv1.m
% https://www.mathworks.com/help/matlab/ref/conv.html
u = [1 1 1];
v = [1 1 0 0 0 1 1];
w = conv(u,v)

Writing conv1.m


In [ ]:
!octave conv1.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
w =

   1   2   2   1   0   1   2   2   1



In [ ]:
u = [1, 1, 1]
v = [1, 1, 0, 0, 0, 1, 1]
w = np.convolve(u, v)
w

array([1, 2, 2, 1, 0, 1, 2, 2, 1])

# Matrix multiplication

In [ ]:
%%writefile matmul.m
% https://www.tutorialspoint.com/matlab/matlab_matrix_multiplication.htm
a = [ 1 2 3; 2 3 4; 1 2 5]
b = [ 2 1 3 ; 5 0 -2; 2 3 -1]
prod = a * b

Writing matmul.m


In [ ]:
!octave matmul.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
a =

   1   2   3
   2   3   4
   1   2   5

b =

   2   1   3
   5   0  -2
   2   3  -1

prod =

   18   10   -4
   27   14   -4
   22   16   -6



In [ ]:
a = np.array([[1, 2, 3], [2, 3, 4], [1, 2, 5]])
b = np.array([[2, 1, 3], [5, 0, -2], [2, 3, -1]])
prod = a @ b
prod

array([[18, 10, -4],
       [27, 14, -4],
       [22, 16, -6]])

# Element-wise multiplication

In [ ]:
%%writefile ew_matmul.m
a = [ 1 2 3; 2 3 4; 1 2 5]
b = [ 2 1 3 ; 5 0 -2; 2 3 -1]
prod = a .* b

Writing ew_matmul.m


In [ ]:
!octave ew_matmul.m

octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
a =

   1   2   3
   2   3   4
   1   2   5

b =

   2   1   3
   5   0  -2
   2   3  -1

prod =

    2    2    9
   10    0   -8
    2    6   -5



In [ ]:
prod = a * b
prod

array([[ 2,  2,  9],
       [10,  0, -8],
       [ 2,  6, -5]])