In [1]:
import tensorflow as tf
print(tf.__version__)

2.7.0


In [4]:
tf.constant(5)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [6]:
vec = tf.constant([2, 3])
vec.ndim

1

In [8]:
vec

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [11]:
mat = tf.constant([[2, 5], [3, 7]])

In [13]:
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 5],
       [3, 7]], dtype=int32)>

In [15]:
assert mat.ndim == 2

In [18]:
mat2 = tf.constant([[2., 3.], [7., 3.]], dtype=tf.float16)

In [19]:
mat2

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2., 3.],
       [7., 3.]], dtype=float16)>

In [22]:
mat2.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[2., 3.],
       [7., 3.]], dtype=float16)>>

In [28]:
rand = tf.random.Generator.from_seed(42)

In [25]:
rand

In [29]:
rand = rand.normal(shape=(3, 2))

In [30]:
rand

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [32]:
tf.zeros([3, 5])

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [33]:
rand[-1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.23193763, -1.8107855 ], dtype=float32)>

In [35]:
rand[0]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-0.7565803 , -0.06854702], dtype=float32)>

In [37]:
rand[:, -1]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.06854702, -1.2573844 , -1.8107855 ], dtype=float32)>