In [1]:
import numpy as np

In [2]:
import librosa

In [3]:
def zcr_rate(wav_in, step=240, sz=960):
    cross = np.abs(np.diff(np.sign(wav_in+1e-8)))
    cross[cross > 1] = 1
    steps=int((np.shape(cross)[0] - sz) / step)
    zrate=np.zeros((steps,))
    for i in range(steps):
        zrate[i]=np.mean(cross[i*step:i*step+sz])
    return zrate

In [4]:
y, sr = librosa.load(librosa.ex('trumpet'))

In [14]:
lr = librosa.feature.zero_crossing_rate(y, hop_length=240, center=False)

In [15]:
len(lr[0])

482

In [8]:
len(zcr_rate(y, step=240, sz=960))

486

In [16]:
absdiff = np.abs(np.diff(np.sign(y+1e-8)))


In [17]:
absdiff

array([0., 0., 2., ..., 2., 2., 2.], dtype=float32)

In [18]:
absdiff[absdiff > 1] = 1


In [20]:
absdiff

array([0., 0., 1., ..., 1., 1., 1.], dtype=float32)

In [21]:
steps=int((np.shape(absdiff)[0] - 960) / 240)


In [22]:
steps

486

In [23]:
zcrate=np.zeros((steps,))


In [24]:
zcrate.shape

(486,)

In [25]:
step = 240
segment = 960
for i in range(steps):
    zcrate[i]=np.mean(absdiff[i*step:i*step+segment])

In [43]:
zcrate

array([0.08645833, 0.090625  , 0.10208333, 0.11041667, 0.11145833,
       0.10833333, 0.109375  , 0.11145833, 0.11354167, 0.11354167,
       0.1125    , 0.11354167, 0.11354167, 0.10625   , 0.09166667,
       0.08541667, 0.07708333, 0.08020833, 0.09166667, 0.096875  ,
       0.10729167, 0.11666667, 0.11770833, 0.115625  , 0.1125    ,
       0.10625   , 0.10625   , 0.10625   , 0.10625   , 0.10833333,
       0.11770833, 0.12083333, 0.1125    , 0.10625   , 0.09479167,
       0.08958333, 0.09375   , 0.09270833, 0.09270833, 0.08958333,
       0.08854166, 0.08854166, 0.08541667, 0.08854166, 0.08854166,
       0.08958333, 0.08854166, 0.090625  , 0.09479167, 0.08958333,
       0.09270833, 0.09375   , 0.10625   , 0.13229166, 0.15104167,
       0.16145833, 0.16145833, 0.14687499, 0.13437501, 0.12291667,
       0.11041667, 0.1125    , 0.11041667, 0.12083333, 0.125     ,
       0.11770833, 0.11458334, 0.10416666, 0.09166667, 0.0875    ,
       0.08229167, 0.07604167, 0.07916667, 0.08229167, 0.08229

In [30]:
lr2 = librosa.feature.zero_crossing_rate(y, frame_length=segment, hop_length=step, center=False)[0]

In [31]:
len(lr2)

487

In [32]:
def zcr_rate(wav_in, step=240, sz=960):
    # Calculate the number of frames (steps) to compute ZCR for
    steps = (len(wav_in) - sz) // step
    
    # Initialize an array to hold ZCR values
    zrate = np.zeros(steps)
    
    # Compute ZCR for each frame
    for i in range(steps):
        start = i * step
        end = start + sz
        frame = wav_in[start:end]
        
        # Compute ZCR for the current frame
        zcr = librosa.feature.zero_crossing_rate(frame, frame_length=sz, hop_length=sz)[0, 0]
        zrate[i] = zcr
        
    return zrate

In [35]:
rimp = zcr_rate(y)

In [37]:
rimp

array([0.04270833, 0.034375  , 0.04270833, 0.05625   , 0.059375  ,
       0.05416667, 0.05208333, 0.05416667, 0.05729167, 0.05729167,
       0.05625   , 0.05520833, 0.05625   , 0.05625   , 0.05625   ,
       0.04895833, 0.034375  , 0.03645833, 0.04166667, 0.04375   ,
       0.04895833, 0.053125  , 0.05833333, 0.06354167, 0.059375  ,
       0.05208333, 0.053125  , 0.05416667, 0.053125  , 0.05208333,
       0.053125  , 0.05625   , 0.06458333, 0.06458333, 0.04791667,
       0.04166667, 0.046875  , 0.046875  , 0.046875  , 0.04479167,
       0.04479167, 0.04479167, 0.04270833, 0.04375   , 0.04270833,
       0.04479167, 0.04583333, 0.04479167, 0.04270833, 0.04583333,
       0.05104167, 0.04375   , 0.040625  , 0.05      , 0.06458333,
       0.08229167, 0.08541667, 0.07916667, 0.07604167, 0.06770833,
       0.05833333, 0.05416667, 0.05208333, 0.05625   , 0.05833333,
       0.06354167, 0.06666667, 0.05416667, 0.04791667, 0.05      ,
       0.04375   , 0.0375    , 0.03854167, 0.03854167, 0.04062

In [38]:
zcrate

array([0.08645833, 0.090625  , 0.10208333, 0.11041667, 0.11145833,
       0.10833333, 0.109375  , 0.11145833, 0.11354167, 0.11354167,
       0.1125    , 0.11354167, 0.11354167, 0.10625   , 0.09166667,
       0.08541667, 0.07708333, 0.08020833, 0.09166667, 0.096875  ,
       0.10729167, 0.11666667, 0.11770833, 0.115625  , 0.1125    ,
       0.10625   , 0.10625   , 0.10625   , 0.10625   , 0.10833333,
       0.11770833, 0.12083333, 0.1125    , 0.10625   , 0.09479167,
       0.08958333, 0.09375   , 0.09270833, 0.09270833, 0.08958333,
       0.08854166, 0.08854166, 0.08541667, 0.08854166, 0.08854166,
       0.08958333, 0.08854166, 0.090625  , 0.09479167, 0.08958333,
       0.09270833, 0.09375   , 0.10625   , 0.13229166, 0.15104167,
       0.16145833, 0.16145833, 0.14687499, 0.13437501, 0.12291667,
       0.11041667, 0.1125    , 0.11041667, 0.12083333, 0.125     ,
       0.11770833, 0.11458334, 0.10416666, 0.09166667, 0.0875    ,
       0.08229167, 0.07604167, 0.07916667, 0.08229167, 0.08229

In [ ]:
def zcr_rate(wav_in, step=240, segment=960):
    # Calculate the sign of the signal values and shift the result to avoid zero values
    sign_wav = np.sign(wav_in + 1e-8)
    
    # Calculate the absolute difference of the sign changes, this gives 2 at zero crossings
    cross = np.abs(np.diff(sign_wav))
    
    # Clip values greater than 1 to 1 (since only sign changes are considered crossings)
    cross[cross > 1] = 1
    
    # Determine the number of segments (frames) that will be analyzed
    steps = int((np.shape(cross)[0] - segment) / step)
    
    # Initialize an array to store the zero-crossing rates for each segment
    zrate = np.zeros((steps,))
    
    # Loop over each segment to calculate the zero-crossing rate
    for i in range(steps):
        # Calculate the mean of the zero crossings in the current segment
        zrate[i] = np.mean(cross[i*step:i*step+segment])
    
    # Return the array of zero-crossing rates
    return zrate

In [34]:
import numpy as np

def zero_crossing_rate(signal):
    """
    Calculate the zero-crossing rate of a signal.

    Parameters:
    signal (numpy array): Input signal array.

    Returns:
    float: Zero-crossing rate.
    """
    T = len(signal)
    # Calculate the product of each sample with the previous one
    crossings = signal[:-1] * signal[1:]
    # Count the number of times the product is negative (crossing zero)
    zcr = np.sum(crossings < 0) / (T - 1)
    return zcr

# Example usage
signal = np.array([1, -1, 1, -1, 1, -1])
zcr = zero_crossing_rate(signal)
print(f"Zero-crossing rate: {zcr}")


Zero-crossing rate: 1.0


In [39]:
import numpy as np
from numba import njit

@njit
def zcr_rate(wav_in, step=240, segment=960):
    # Calculate the sign of the signal values and shift to avoid zero values
    sign_wav = np.sign(wav_in + 1e-8)

    absdiff = np.abs(np.diff(sign_wav))

    for i in range(len(absdiff)):
        if absdiff[i] > 1:
            absdiff[i] = 1

    steps = (len(absdiff) - segment) // step

    zcrate = np.zeros(steps)

    for i in range(steps):
        start_idx = i * step
        end_idx = start_idx + segment
        zcrate[i] = np.mean(absdiff[start_idx:end_idx])

    return zcrate

In [40]:
zr = zcr_rate(y)

In [44]:
zr

array([0.08645833, 0.090625  , 0.10208333, 0.11041667, 0.11145833,
       0.10833333, 0.109375  , 0.11145833, 0.11354167, 0.11354167,
       0.1125    , 0.11354167, 0.11354167, 0.10625   , 0.09166667,
       0.08541667, 0.07708333, 0.08020833, 0.09166667, 0.096875  ,
       0.10729167, 0.11666667, 0.11770833, 0.115625  , 0.1125    ,
       0.10625   , 0.10625   , 0.10625   , 0.10625   , 0.10833333,
       0.11770833, 0.12083333, 0.1125    , 0.10625   , 0.09479167,
       0.08958333, 0.09375   , 0.09270833, 0.09270833, 0.08958333,
       0.08854167, 0.08854167, 0.08541667, 0.08854167, 0.08854167,
       0.08958333, 0.08854167, 0.090625  , 0.09479167, 0.08958333,
       0.09270833, 0.09375   , 0.10625   , 0.13229167, 0.15104167,
       0.16145833, 0.16145833, 0.146875  , 0.134375  , 0.12291667,
       0.11041667, 0.1125    , 0.11041667, 0.12083333, 0.125     ,
       0.11770833, 0.11458333, 0.10416667, 0.09166667, 0.0875    ,
       0.08229167, 0.07604167, 0.07916667, 0.08229167, 0.08229

In [49]:
np.allclose(zr, zcrate)

True

In [50]:
%pip install h5py

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 10.3 MB/s eta 0:00:0000:010:01
Note: you may need to restart the kernel to use updated packages.


In [51]:
import h5py